import type { NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import useGreeting from '@lib/greetings/useGreeting';
import WithAuthentication from '@components/WithAuthentication';

const Home: NextPage = () => {
  const { status, data } = useSession();
  const { data: greeting } = useGreeting({
    name: data?.user?.email || '',
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack rowGap={1}>
        <Typography variant="h4" component="h1">
          {greeting ? greeting.greeting : 'Hello'}
        </Typography>
        {status === 'unauthenticated' && (
          <Button color="primary" variant="contained" onClick={() => signIn()}>
            Sign in
          </Button>
        )}
        {status === 'authenticated' && (
          <Button color="primary" variant="contained" onClick={() => signOut()}>
            Sign out
          </Button>
        )}
      </Stack>
    </>
  );
};

export default WithAuthentication(Home);
